apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: {{ include "core-applications.name" . }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "core-applications.labels" . | nindent 4 }}
spec:
  description: Core components of k8s cluster
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
