apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    {{- include "core-applications.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: {{ include "core-applications.name" . }}
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.26.3
    helm:
      values: |
        server:
          extraArgs:
            - --insecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
